### ISSUE TITLE
Add support for "sensitive" or private options.

### ISSUE THREAD

**Issue by ctipperCMU** [LearnSphere/WorkflowComponents#38]
Phil brought up the point that the ImportXAPI component requires a user id and password but that if the workflow is public those options shouldn't be viewable by others. We need to add support for 'sensitive' or private options that are only viewable by the workflow owner. Nothing elaborate is needed, just a means for tagging the options in the xsd and then not including them in the options panel when appropriate.

**Comment by pschaldenbrand** [comment]
To set an option as private, you add the attribute ls:privateOption="true". The option must be of type xs:string. If you don't add this attribute to an option it defaults to false. Anonymize now uses a private option. See https://github.com/LearnSphere/WorkflowComponents/blob/dev/Anonymize/schemas/Anonymize_v1_0.xsd for an example.

Opening a workflow as its owner:
* You will see the value of the private option. You can click the checkbox next to "Display private options" to convert the value to dots (likely intended for screenshots).

Opening a workflow NOT as its owner:
* You will see six dots instead of the value of the private option.
The lock icon next to the option indicates whether it is a private option. It should have a useful tooltip.

This feature will be available with the release of DataShop v10.3.
